# Generated by Django 2.2.12 on 2021-09-06 17:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ways', models.IntegerField(default=2)),
                ('num_sets', models.IntegerField(default=4)),
                ('block_size', models.IntegerField(default=8)),
                ('address_bits', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='CachePattern',
            fields=[
                ('pattern_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_size', models.IntegerField(default=2)),
                ('accesses_raw', models.TextField()),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.CacheParameters')),
            ],
        ),
        migrations.CreateModel(
            name='PatternQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('for_user', models.TextField()),
                ('ask_evict', models.BooleanField(default=True)),
                ('index', models.IntegerField()),
                ('give_first', models.IntegerField(default=5)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.CachePattern')),
            ],
        ),
        migrations.CreateModel(
            name='PatternAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_results_raw', models.TextField()),
                ('final_state_raw', models.TextField()),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('was_complete', models.BooleanField(default=False)),
                ('was_save', models.BooleanField(default=False)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('for_user', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.PatternQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('for_user', models.TextField()),
                ('missing_parts_raw', models.TextField()),
                ('given_parts_raw', models.TextField()),
                ('index', models.IntegerField()),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.CacheParameters')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_user', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('answer_raw', models.TextField()),
                ('was_complete', models.BooleanField()),
                ('was_save', models.BooleanField()),
                ('score', models.IntegerField()),
                ('score_ratio', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.ParameterQuestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='patternquestion',
            index=models.Index(fields=['for_user', 'index'], name='exercises_p_for_use_96c710_idx'),
        ),
        migrations.AddIndex(
            model_name='patternanswer',
            index=models.Index(fields=['for_user', 'submit_time'], name='exercises_p_for_use_f6821d_idx'),
        ),
        migrations.AddIndex(
            model_name='patternanswer',
            index=models.Index(fields=['for_user', 'was_complete', 'score'], name='exercises_p_for_use_3ebe90_idx'),
        ),
        migrations.AddIndex(
            model_name='parameteranswer',
            index=models.Index(fields=['for_user', 'submit_time'], name='exercises_p_for_use_3b491b_idx'),
        ),
        migrations.AddIndex(
            model_name='parameteranswer',
            index=models.Index(fields=['for_user', 'was_complete', 'score_ratio'], name='exercises_p_for_use_a08f91_idx'),
        ),
    ]
