# Generated by Django 2.0.3 on 2018-03-15 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('quiz', '0001_initial'), ('quiz', '0002_auto_20180305_0216'), ('quiz', '0003_auto_20180305_1619'), ('quiz', '0004_auto_20180310_2148'), ('quiz', '0005_patternanswer_was_complete'), ('quiz', '0006_auto_20180311_1755'), ('quiz', '0007_patternquestion_ask_evict'), ('quiz', '0008_auto_20180311_2218'), ('quiz', '0009_auto_20180311_2246'), ('quiz', '0010_patternanswer_for_user')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatternAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_results_raw', models.TextField()),
                ('final_state_raw', models.TextField()),
                ('score', models.IntegerField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.CacheQuestion')),
                ('was_complete', models.BooleanField(default=False)),
                ('for_user', models.TextField(default='test')),
            ],
        ),
        migrations.CreateModel(
            name='CacheParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ways', models.IntegerField(default=2)),
                ('num_indices', models.IntegerField(default=4)),
                ('entry_size', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CachePattern',
            fields=[
                ('pattern_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_size', models.IntegerField(default=2)),
                ('address_bits', models.IntegerField(default=8)),
                ('accesses_raw', models.TextField()),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.CacheParameters')),
            ],
        ),
        migrations.CreateModel(
            name='PatternQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('for_user', models.TextField()),
                ('index', models.IntegerField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.CachePattern')),
                ('ask_evict', models.BooleanField(default=True)),
                ('give_first', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterField(
            model_name='cacheparameters',
            name='entry_size',
            field=models.IntegerField(default=8),
        ),
    ]
