# Generated by Django 2.0.2 on 2018-03-04 22:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_results', models.TextField()),
                ('final_state', models.TextField()),
                ('score', models.IntegerField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CacheParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ways', models.IntegerField(default=2)),
                ('num_indices', models.IntegerField(default=4)),
                ('entry_size', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CachePattern',
            fields=[
                ('pattern_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_size', models.IntegerField(default=2)),
                ('address_bits', models.IntegerField(default=9)),
                ('accesses_raw', models.TextField()),
                ('access_results_raw', models.TextField()),
                ('final_state_raw', models.TextField()),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.CacheParameters')),
            ],
        ),
        migrations.CreateModel(
            name='CacheQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('for_user', models.TextField()),
                ('index', models.IntegerField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.CacheParameters')),
            ],
        ),
        migrations.AddField(
            model_name='cacheanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.CacheQuestion'),
        ),
    ]
