# Generated by Django 2.0.2 on 2018-03-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachequestion',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.CachePattern'),
        ),
    ]
