# Generated by Django 2.0.3 on 2018-03-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_squashed_0010_patternanswer_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternanswer',
            name='was_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patternanswer',
            name='for_user',
            field=models.TextField(),
        ),
    ]
