# Generated by Django 2.0.3 on 2018-03-16 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180315_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_user', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('answer_raw', models.TextField()),
                ('was_complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ParameterQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('for_user', models.TextField()),
                ('address_bits', models.IntegerField()),
                ('missing_parts_raw', models.TextField()),
                ('given_parts_raw', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='cacheparameters',
            old_name='entry_size',
            new_name='block_size',
        ),
        migrations.RenameField(
            model_name='cacheparameters',
            old_name='num_indices',
            new_name='num_sets',
        ),
        migrations.AddField(
            model_name='parameterquestion',
            name='parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.CacheParameters'),
        ),
        migrations.AddField(
            model_name='parameteranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.ParameterQuestion'),
        ),
    ]
