# Generated by Django 2.0.2 on 2018-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('quiz', '0002_auto_20180305_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CacheAnswer',
            new_name='PatternAnswer',
        ),
        migrations.RenameModel(
            old_name='CacheQuestion',
            new_name='PatternQuestion',
        ),
        migrations.RenameField(
            model_name='patternanswer',
            old_name='access_results',
            new_name='access_results_raw',
        ),
        migrations.RenameField(
            model_name='patternanswer',
            old_name='final_state',
            new_name='final_state_raw',
        ),
        migrations.AlterField(
            model_name='cacheparameters',
            name='entry_size',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='cachepattern',
            name='address_bits',
            field=models.IntegerField(default=6),
        ),
    ]
