# Generated by Django 2.0.2 on 2018-03-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180305_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachepattern',
            name='access_results_raw',
        ),
        migrations.RemoveField(
            model_name='cachepattern',
            name='final_state_raw',
        ),
    ]
