# Generated by Django 2.0.3 on 2018-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180316_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterquestion',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
