# Generated by Django 2.0.2 on 2018-03-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180310_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternanswer',
            name='was_complete',
            field=models.BooleanField(default=False),
        ),
    ]
