# Generated by Django 2.0.3 on 2018-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_parameterquestion_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachepattern',
            name='address_bits',
        ),
        migrations.RemoveField(
            model_name='parameterquestion',
            name='address_bits',
        ),
        migrations.AddField(
            model_name='cacheparameters',
            name='address_bits',
            field=models.IntegerField(default=8),
        ),
    ]
