# Generated by Django 2.0.2 on 2018-03-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20180316_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameteranswer',
            name='score',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameteranswer',
            name='score_ratio',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='patternanswer',
            index=models.Index(fields=['for_user', 'submit_time'], name='quiz_patter_for_use_cad271_idx'),
        ),
        migrations.AddIndex(
            model_name='patternanswer',
            index=models.Index(fields=['for_user', 'was_complete', 'score'], name='quiz_patter_for_use_3a2f34_idx'),
        ),
        migrations.AddIndex(
            model_name='parameteranswer',
            index=models.Index(fields=['for_user', 'submit_time'], name='quiz_parame_for_use_5d073c_idx'),
        ),
        migrations.AddIndex(
            model_name='parameteranswer',
            index=models.Index(fields=['for_user', 'was_complete', 'score_ratio'], name='quiz_parame_for_use_382ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='patternquestion',
            index=models.Index(fields=['for_user', 'index'], name='quiz_patter_for_use_c1f75d_idx'),
        ),
    ]
