# Generated by Django 2.0.2 on 2018-03-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_patternanswer_was_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachepattern',
            name='address_bits',
            field=models.IntegerField(default=8),
        ),
    ]
