# Generated by Django 2.0.2 on 2018-03-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180311_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternquestion',
            name='ask_evict',
            field=models.BooleanField(default=False),
        ),
    ]
