# Generated by Django 2.0.2 on 2018-03-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180317_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameteranswer',
            name='was_save',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
