# Generated by Django 2.0.2 on 2018-03-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_patternquestion_ask_evict'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternquestion',
            name='give_first',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='patternquestion',
            name='ask_evict',
            field=models.BooleanField(default=True),
        ),
    ]
