# Generated by Django 2.0.2 on 2018-03-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180311_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternquestion',
            name='give_first',
            field=models.IntegerField(default=5),
        ),
    ]
