# Generated by Django 2.0.2 on 2018-03-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20180311_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternanswer',
            name='for_user',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
